import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FloatingIcons from "@/components/FloatingIcons";
import AdminFloatingButton from "@/components/auth/AdminFloatingButton";
import ClientProviders from "@/components/ClientProviders";
import { PreFlopPlannerProvider } from "@/components/PreFlopPlannerContext";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black min-h-screen`}
      >
        <ClientProviders>
          <PreFlopPlannerProvider>
            <Navbar />
            <div className="pt-20">{children}</div>
            <FloatingIcons />
            <AdminFloatingButton />
          </PreFlopPlannerProvider>
        </ClientProviders>
      </body>
    </html>
  );
}
